using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using System;

[RequireComponent(typeof(CharacterController))]
public class Character : MonoBehaviour
{
    CharacterController controller;

    [Header("PlayerSettings")]
    [Space(2)]
    [Tooltip("Speed Value between 1 and 6")]
    [Range(1.0f, 6.0f)]
    public float speed = 6;
    public float gravity = 9.81f;
    public float jumpSpeed = 10.0f;

    enum ControllerType { SimpleMove, Move }
    [SerializeField] ControllerType type;

    Vector3 moveDirection;

    [Header("Weapon Settings")]
    [Space(10)]
    public float projectileForce;
    public Rigidbody projectilePrefab;
    public Transform projectileSpawnpoint;


    // Start is called before the first frame update
    void Start()
    {

        try
        {
            controller = GetComponent<CharacterController>();

            controller.minMoveDistance = 0.0f;

            if (speed <= 0)
            {
                speed = 6.0f;
                throw new UnassignedReferenceException("Speed not set on" + name + "defaulting to" + speed);
            }

            if (jumpSpeed <= 0)
            {
                jumpSpeed = 6.0f;

                Debug.Log("JumpSpeed not set on" + name + "defaulting to" + jumpSpeed);
            }

            if (gravity <= 0)
            {
                gravity = 9.81f;

                Debug.Log("Gravity not set on" + name + "defaulting to" + gravity);
            }

            moveDirection = Vector3.zero;

            if (projectileForce <= 0)
            {
                projectileForce = 10.0f;

                Debug.Log("ProjectileForce not set on" + name + "defaulting to" + projectileForce);
            }

            if (!projectilePrefab)
                Debug.Log("Missing projectilePrefab on" + name);

            if (!projectileSpawnpoint)
                Debug.Log("Missing projectileSpawnPoint on" + name);

        }
        catch (NullReferenceException e)
        {
            Debug.LogWarning(e.Message);
        }
        catch (UnassignedReferenceException e)
        {
            Debug.LogWarning(e.Message);
        }
        finally
        {
            Debug.LogWarning("Always Get Called");
        }

        if (projectileForce <= 0)
            projectileForce = 10.0f;
    }

    // Update is called once per frame
    void Update()
    {
        switch (type)
        {
            case ControllerType.SimpleMove:
                controller.SimpleMove(transform.forward * Input.GetAxis("vertical") * speed);

                break;
            case ControllerType.Move:

                if (controller.isGrounded)
                {
                    moveDirection = new Vector3(Input.GetAxis("Horizontal"), 0, Input.GetAxis("Vertical"));
                    moveDirection *= speed;

                    moveDirection = transform.TransformDirection(moveDirection);
                    if (Input.GetButtonDown("Jump"))
                        moveDirection.y = jumpSpeed;
                }

                moveDirection.y -= gravity * Time.deltaTime;
                controller.Move(moveDirection * Time.deltaTime);

                break;


        }

        if (Input.GetButtonDown("Fire1"))
            Fire();
    }

    void Fire()
    {
        if (projectilePrefab && projectileSpawnpoint)
        {
            Rigidbody temp = Instantiate(projectilePrefab, projectileSpawnpoint.position, projectileSpawnpoint.rotation);

            temp.AddForce(projectileSpawnpoint.forward * projectileForce, ForceMode.Impulse);

            Destroy(temp.gameObject, 2.0f);
        }
    }
}
    